apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: interessemelding
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/interessemelding:latest
  team: teamtag
  port: 80
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
