apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tag-kontaktskjema
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tag-kontaktskjema:latest
  team: teamtag
  port: 8080
  secrets: true
  ingresses:
    - https://arbeidsgiver.nav.no/kontaktskjema
  liveness:
    path: /kontaktskjema/isAlive
    initialDelay: 40
  readiness:
    path: /kontaktskjema/isReady
    initialDelay: 40
