apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tag-kontaktskjema-uthenting
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tag-kontaktskjema:latest
  team: teamtag
  port: 8080
  secrets: true
  ingresses:
    - https://arbeidsgiver-q.nav.no/kontaktskjemaUthenting
    - https://tag-kontaktskjema-uthenting.nais.oera-q.local
  liveness:
    path: /kontaktskjema/internal/actuator/info
    initialDelay: 40
  readiness:
    path: /kontaktskjema/internal/actuator/info
    initialDelay: 40
  env:
  - name: CONTROLLER_BASEPATH
    value: /kontaktskjemaUthenting
  - name: FEATURE_TOGGLE_UTHENTINGSENDEPUNKT
    value: enabled
prometheus:
  enabled: true
  path: /kontaktskjema/internal/actuator/prometheus
